name: Publish Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: CGA1123
          password: ${{ secrets.PERSONAL_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          build-args: CACHE=$(date +s)
          cache-from: type=registry,ref=ghcr.io/cga1123/dependabot-lein-runner:latest
          cache-to: type=inline
          tags: |
            ghcr.io/cga1123/dependabot-lein-runner:${{ github.sha }}
            ghcr.io/cga1123/dependabot-lein-runner:latest
