name: Daily Scheduled Bump
on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./
        with:
          token: ${{ github.token }}
          directory: '/dummy'
          repository: ${{ github.repository }}
